	rangefinder_sopc u0 (
		.clk_clk                           (<connected-to-clk_clk>),                           //                 clk.clk
		.reset_reset_n                     (<connected-to-reset_reset_n>),                     //               reset.reset_n
		.sys_timer_export                  (<connected-to-sys_timer_export>),                  //           sys_timer.export
		.pc_uart_rxd                       (<connected-to-pc_uart_rxd>),                       //             pc_uart.rxd
		.pc_uart_txd                       (<connected-to-pc_uart_txd>),                       //                    .txd
		.leds_port_export                  (<connected-to-leds_port_export>),                  //           leds_port.export
		.i2c_port_export                   (<connected-to-i2c_port_export>),                   //            i2c_port.export
		.laser_driver_ref_clk              (<connected-to-laser_driver_ref_clk>),              //        laser_driver.ref_clk
		.laser_driver_driver_enable        (<connected-to-laser_driver_driver_enable>),        //                    .driver_enable
		.laser_driver_laser                (<connected-to-laser_driver_laser>),                //                    .laser
		.laser_driver_comparator           (<connected-to-laser_driver_comparator>),           //                    .comparator
		.spi_tdc_master_clk                (<connected-to-spi_tdc_master_clk>),                //             spi_tdc.master_clk
		.spi_tdc_master_csn                (<connected-to-spi_tdc_master_csn>),                //                    .master_csn
		.spi_tdc_master_mosi               (<connected-to-spi_tdc_master_mosi>),               //                    .master_mosi
		.spi_tdc_master_miso               (<connected-to-spi_tdc_master_miso>),               //                    .master_miso
		.pulse_generator_start_pulse       (<connected-to-pulse_generator_start_pulse>),       //     pulse_generator.start_pulse
		.pulse_generator_stop_pulse        (<connected-to-pulse_generator_stop_pulse>),        //                    .stop_pulse
		.spi_vga_master_clk                (<connected-to-spi_vga_master_clk>),                //             spi_vga.master_clk
		.spi_vga_master_csn                (<connected-to-spi_vga_master_csn>),                //                    .master_csn
		.spi_vga_master_mosi               (<connected-to-spi_vga_master_mosi>),               //                    .master_mosi
		.spi_vga_master_miso               (<connected-to-spi_vga_master_miso>),               //                    .master_miso
		.rs485_de_export                   (<connected-to-rs485_de_export>),                   //            rs485_de.export
		.tdc_enable_export                 (<connected-to-tdc_enable_export>),                 //          tdc_enable.export
		.system_mode_export                (<connected-to-system_mode_export>),                //         system_mode.export
		.amp_gain_export                   (<connected-to-amp_gain_export>),                   //            amp_gain.export
		.apd_overcurrent_export            (<connected-to-apd_overcurrent_export>),            //     apd_overcurrent.export
		.spi_apd_master_clk                (<connected-to-spi_apd_master_clk>),                //             spi_apd.master_clk
		.spi_apd_master_csn                (<connected-to-spi_apd_master_csn>),                //                    .master_csn
		.spi_apd_master_mosi               (<connected-to-spi_apd_master_mosi>),               //                    .master_mosi
		.spi_apd_master_miso               (<connected-to-spi_apd_master_miso>),               //                    .master_miso
		.iris_motor_dir                    (<connected-to-iris_motor_dir>),                    //                iris.motor_dir
		.iris_motor_step                   (<connected-to-iris_motor_step>),                   //                    .motor_step
		.iris_motor_en                     (<connected-to-iris_motor_en>),                     //                    .motor_en
		.atten_motor_dir                   (<connected-to-atten_motor_dir>),                   //               atten.motor_dir
		.atten_motor_step                  (<connected-to-atten_motor_step>),                  //                    .motor_step
		.atten_motor_en                    (<connected-to-atten_motor_en>),                    //                    .motor_en
		.laser_charge_ref_clk              (<connected-to-laser_charge_ref_clk>),              //        laser_charge.ref_clk
		.laser_charge_driver_enable        (<connected-to-laser_charge_driver_enable>),        //                    .driver_enable
		.laser_charge_laser                (<connected-to-laser_charge_laser>),                //                    .laser
		.laser_charge_comparator           (<connected-to-laser_charge_comparator>),           //                    .comparator
		.tdc_start_pulse_gen_ref_clk       (<connected-to-tdc_start_pulse_gen_ref_clk>),       // tdc_start_pulse_gen.ref_clk
		.tdc_start_pulse_gen_driver_enable (<connected-to-tdc_start_pulse_gen_driver_enable>), //                    .driver_enable
		.tdc_start_pulse_gen_laser         (<connected-to-tdc_start_pulse_gen_laser>),         //                    .laser
		.tdc_start_pulse_gen_comparator    (<connected-to-tdc_start_pulse_gen_comparator>),    //                    .comparator
		.adc_clk_clk                       (<connected-to-adc_clk_clk>),                       //             adc_clk.clk
		.adc_data_adc_data                 (<connected-to-adc_data_adc_data>),                 //            adc_data.adc_data
		.adc_data_comparator               (<connected-to-adc_data_comparator>)                //                    .comparator
	);

